using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FoenixIDE
{
    public class KeyboardMap
    {
        // 
        // Modifiers
        // 
        public const int KEY_ShiftKey = 1;                // The SHIFT key.
        public const int KEY_ControlKey = 2;              // The CTRL key.
        public const int KEY_Alt = 4;                     // The ALT or CBM key.
        public const int KEY_CapsLock = 8;                // The CAPS LOCK key.
        public const int KEY_NumLock = 16;                // The NUM LOCK key.
        public const int KEY_Scroll = 32;                 // The SCROLL LOCK key.
        public const int KEY_LOGO = 64;                   // The left Windows logo key on a "Windows 95" keyboard.
        public const int KEY_NonPrintable = 128;          // The lower byte is a raw keycode, not an ASCII symbol.

        // 
        // Keyboard Codes
        // 
        public const int KEY_None = 0;                    // No key pressed.
        public const int KEY_LButton = 1;                 // The left mouse button.
        public const int KEY_RButton = 2;                 // The right mouse button.
        public const int KEY_Cancel = 3;                  // The CANCEL key.
        public const int KEY_MButton = 4;                 // The middle mouse button (three-button mouse).
        public const int KEY_XButton1 = 5;                // The first x mouse button (five-button mouse).
        public const int KEY_XButton2 = 6;                // The second x mouse button (five-button mouse).
        public const int KEY_Back = 8;                    // The BACKSPACE key.
        public const int KEY_Tab = 9;                     // The TAB key.
        public const int KEY_LineFeed = 10;               // The LINEFEED key.
        public const int KEY_Clear = 12;                  // The CLEAR key.
        public const int KEY_Return = 13;                 // The RETURN key.
        public const int KEY_Enter = 13;                  // The ENTER key.
        public const int KEY_Pause = 19;                  // The PAUSE key.
        public const int KEY_KanaMode = 21;               // The IME Kana mode key.
        public const int KEY_HanguelMode = 21;            // The IME Hanguel mode key. (maintained for compatibility; use HangulMode)
        public const int KEY_HangulMode = 21;             // The IME Hangul mode key.
        public const int KEY_JunjaMode = 23;              // The IME Junja mode key.
        public const int KEY_FinalMode = 24;              // The IME final mode key.
        public const int KEY_HanjaMode = 25;              // The IME Hanja mode key.
        public const int KEY_KanjiMode = 25;              // The IME Kanji mode key.
        public const int KEY_Escape = 27;                 // The ESC key.
        public const int KEY_IMEConvert = 28;             // The IME convert key.
        public const int KEY_IMENonconvert = 29;          // The IME nonconvert key.
        public const int KEY_IMEAccept = 30;              // The IME accept key replaces System.Windows.Forms.Keys.IMEAceept.
        public const int KEY_IMEAceept = 30;              // The IME accept key. Obsolete use System.Windows.Forms.Keys.IMEAccept instead.
        public const int KEY_IMEModeChange = 31;          // The IME mode change key.
        public const int KEY_Space = 32;                  // The SPACEBAR key.
        public const int KEY_Prior = 33;                  // The PAGE UP key.
        public const int KEY_PageUp = 33;                 // The PAGE UP key.
        public const int KEY_Next = 34;                   // The PAGE DOWN key.
        public const int KEY_PageDown = 34;               // The PAGE DOWN key.
        public const int KEY_End = 35;                    // The END key.
        public const int KEY_Home = 36;                   // The HOME key.
        public const int KEY_Left = 37;                   // The LEFT ARROW key.
        public const int KEY_Up = 38;                     // The UP ARROW key.
        public const int KEY_Right = 39;                  // The RIGHT ARROW key.
        public const int KEY_Down = 40;                   // The DOWN ARROW key.
        public const int KEY_Select = 41;                 // The SELECT key.
        public const int KEY_Print = 42;                  // The PRINT key.
        public const int KEY_Execute = 43;                // The EXECUTE key.
        public const int KEY_Snapshot = 44;               // The PRINT SCREEN key.
        public const int KEY_PrintScreen = 44;            // The PRINT SCREEN key.
        public const int KEY_Insert = 45;                 // The INS key.
        public const int KEY_Delete = 46;                 // The DEL key.
        public const int KEY_Help = 47;                   // The HELP key.
        public const int KEY_D0 = 48;                     // The 0 key.
        public const int KEY_D1 = 49;                     // The 1 key.
        public const int KEY_D2 = 50;                     // The 2 key.
        public const int KEY_D3 = 51;                     // The 3 key.
        public const int KEY_D4 = 52;                     // The 4 key.
        public const int KEY_D5 = 53;                     // The 5 key.
        public const int KEY_D6 = 54;                     // The 6 key.
        public const int KEY_D7 = 55;                     // The 7 key.
        public const int KEY_D8 = 56;                     // The 8 key.
        public const int KEY_D9 = 57;                     // The 9 key.
        public const int KEY_A = 65;                      // The A key.
        public const int KEY_B = 66;                      // The B key.
        public const int KEY_C = 67;                      // The C key.
        public const int KEY_D = 68;                      // The D key.
        public const int KEY_E = 69;                      // The E key.
        public const int KEY_F = 70;                      // The F key.
        public const int KEY_G = 71;                      // The G key.
        public const int KEY_H = 72;                      // The H key.
        public const int KEY_I = 73;                      // The I key.
        public const int KEY_J = 74;                      // The J key.
        public const int KEY_K = 75;                      // The K key.
        public const int KEY_L = 76;                      // The L key.
        public const int KEY_M = 77;                      // The M key.
        public const int KEY_N = 78;                      // The N key.
        public const int KEY_O = 79;                      // The O key.
        public const int KEY_P = 80;                      // The P key.
        public const int KEY_Q = 81;                      // The Q key.
        public const int KEY_R = 82;                      // The R key.
        public const int KEY_S = 83;                      // The S key.
        public const int KEY_T = 84;                      // The T key.
        public const int KEY_U = 85;                      // The U key.
        public const int KEY_V = 86;                      // The V key.
        public const int KEY_W = 87;                      // The W key.
        public const int KEY_X = 88;                      // The X key.
        public const int KEY_Y = 89;                      // The Y key.
        public const int KEY_Z = 90;                      // The Z key.
        public const int KEY_LWin = 91;                   // The left Windows logo key (Microsoft Natural Keyboard).
        public const int KEY_RWin = 92;                   // The right Windows logo key (Microsoft Natural Keyboard).
        public const int KEY_Apps = 93;                   // The application key (Microsoft Natural Keyboard).
        public const int KEY_Sleep = 95;                  // The computer sleep key.
        public const int KEY_NumPad0 = 96;                // The 0 key on the numeric keypad.
        public const int KEY_NumPad1 = 97;                // The 1 key on the numeric keypad.
        public const int KEY_NumPad2 = 98;                // The 2 key on the numeric keypad.
        public const int KEY_NumPad3 = 99;                // The 3 key on the numeric keypad.
        public const int KEY_NumPad4 = 100;               // The 4 key on the numeric keypad.
        public const int KEY_NumPad5 = 101;               // The 5 key on the numeric keypad.
        public const int KEY_NumPad6 = 102;               // The 6 key on the numeric keypad.
        public const int KEY_NumPad7 = 103;               // The 7 key on the numeric keypad.
        public const int KEY_NumPad8 = 104;               // The 8 key on the numeric keypad.
        public const int KEY_NumPad9 = 105;               // The 9 key on the numeric keypad.
        public const int KEY_Multiply = 106;              // The multiply key.
        public const int KEY_Add = 107;                   // The add key.
        public const int KEY_Separator = 108;             // The separator key.
        public const int KEY_Subtract = 109;              // The subtract key.
        public const int KEY_Decimal = 110;               // The decimal key.
        public const int KEY_Divide = 111;                // The divide key.
        public const int KEY_F1 = 112;                    // The F1 key.
        public const int KEY_F2 = 113;                    // The F2 key.
        public const int KEY_F3 = 114;                    // The F3 key.
        public const int KEY_F4 = 115;                    // The F4 key.
        public const int KEY_F5 = 116;                    // The F5 key.
        public const int KEY_F6 = 117;                    // The F6 key.
        public const int KEY_F7 = 118;                    // The F7 key.
        public const int KEY_F8 = 119;                    // The F8 key.
        public const int KEY_F9 = 120;                    // The F9 key.
        public const int KEY_F10 = 121;                   // The F10 key.
        public const int KEY_F11 = 122;                   // The F11 key.
        public const int KEY_F12 = 123;                   // The F12 key.
        public const int KEY_F13 = 124;                   // The F13 key.
        public const int KEY_F14 = 125;                   // The F14 key.
        public const int KEY_F15 = 126;                   // The F15 key.
        public const int KEY_F16 = 127;                   // The F16 key.
        public const int KEY_F17 = 128;                   // The F17 key.
        public const int KEY_F18 = 129;                   // The F18 key.
        public const int KEY_F19 = 130;                   // The F19 key.
        public const int KEY_F20 = 131;                   // The F20 key.
        public const int KEY_F21 = 132;                   // The F21 key.
        public const int KEY_F22 = 133;                   // The F22 key.
        public const int KEY_F23 = 134;                   // The F23 key.
        public const int KEY_F24 = 135;                   // The F24 key.
        public const int KEY_LShiftKey = 160;             // The left SHIFT key.
        public const int KEY_RShiftKey = 161;             // The right SHIFT key.
        public const int KEY_LControlKey = 162;           // The left CTRL key.
        public const int KEY_RControlKey = 163;           // The right CTRL key.
        public const int KEY_LMenu = 164;                 // The left ALT key.
        public const int KEY_RMenu = 165;                 // The right ALT key.
        public const int KEY_BrowserBack = 166;           // The browser back key (Windows 2000 or later).
        public const int KEY_BrowserForward = 167;        // The browser forward key (Windows 2000 or later).
        public const int KEY_BrowserRefresh = 168;        // The browser refresh key (Windows 2000 or later).
        public const int KEY_BrowserStop = 169;           // The browser stop key (Windows 2000 or later).
        public const int KEY_BrowserSearch = 170;         // The browser search key (Windows 2000 or later).
        public const int KEY_BrowserFavorites = 171;      // The browser favorites key (Windows 2000 or later).
        public const int KEY_BrowserHome = 172;           // The browser home key (Windows 2000 or later).
        public const int KEY_VolumeMute = 173;            // The volume mute key (Windows 2000 or later).
        public const int KEY_VolumeDown = 174;            // The volume down key (Windows 2000 or later).
        public const int KEY_VolumeUp = 175;              // The volume up key (Windows 2000 or later).
        public const int KEY_MediaNextTrack = 176;        // The media next track key (Windows 2000 or later).
        public const int KEY_MediaPreviousTrack = 177;    // The media previous track key (Windows 2000 or later).
        public const int KEY_MediaStop = 178;             // The media Stop key (Windows 2000 or later).
        public const int KEY_MediaPlayPause = 179;        // The media play pause key (Windows 2000 or later).
        public const int KEY_LaunchMail = 180;            // The launch mail key (Windows 2000 or later).
        public const int KEY_SelectMedia = 181;           // The select media key (Windows 2000 or later).
        public const int KEY_LaunchApplication1 = 182;    // The start application one key (Windows 2000 or later).
        public const int KEY_LaunchApplication2 = 183;    // The start application two key (Windows 2000 or later).
        public const int KEY_OemSemicolon = 186;          // The OEM Semicolon key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem1 = 186;                  // The OEM 1 key.
        public const int KEY_Oemplus = 187;               // The OEM plus key on any country/region keyboard (Windows 2000 or later).
        public const int KEY_Oemcomma = 188;              // The OEM comma key on any country/region keyboard (Windows 2000 or later).
        public const int KEY_OemMinus = 189;              // The OEM minus key on any country/region keyboard (Windows 2000 or later).
        public const int KEY_OemPeriod = 190;             // The OEM period key on any country/region keyboard (Windows 2000 or later).
        public const int KEY_OemQuestion = 191;           // The OEM question mark key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem2 = 191;                  // The OEM 2 key.
        public const int KEY_Oemtilde = 192;              // The OEM tilde key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem3 = 192;                  // The OEM 3 key.
        public const int KEY_OemOpenBrackets = 219;       // The OEM open bracket key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem4 = 219;                  // The OEM 4 key.
        public const int KEY_OemPipe = 220;               // The OEM pipe key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem5 = 220;                  // The OEM 5 key.
        public const int KEY_OemCloseBrackets = 221;      // The OEM close bracket key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem6 = 221;                  // The OEM 6 key.
        public const int KEY_OemQuotes = 222;             // The OEM singled/double quote key on a US standard keyboard (Windows 2000 or later).
        public const int KEY_Oem7 = 222;                  // The OEM 7 key.
        public const int KEY_Oem8 = 223;                  // The OEM 8 key.
        public const int KEY_OemBackslash = 226;          // or later).
        public const int KEY_Oem102 = 226;                // The OEM 102 key.
        public const int KEY_ProcessKey = 229;            // The PROCESS KEY key.
        public const int KEY_Packet = 231;                // is the low word of a 32-bit virtual-key value used for non-keyboard input methods.
        public const int KEY_Attn = 246;                  // The ATTN key.
        public const int KEY_Crsel = 247;                 // The CRSEL key.
        public const int KEY_Exsel = 248;                 // The EXSEL key.
        public const int KEY_EraseEof = 249;              // The ERASE EOF key.
        public const int KEY_Play = 250;                  // The PLAY key.
        public const int KEY_Zoom = 251;                  // The ZOOM key.
        public const int KEY_NoName = 252;                // A constant reserved for future use.
        public const int KEY_Pa1 = 253;                   // The PA1 key.
        public const int KEY_OemClear = 254;              // The CLEAR key.
    }
}
